### ISSUE TITLE
"Update catalog" hangs

### ISSUE THREAD

**Issue by ilu33** [ephraim/lcurse#20]
`$ lcurse
Traceback (most recent call last):
  File "/opt/lcurse/modules/waitdlg.py", line 252, in run
    self.retrieveListOfAddons()
  File "/opt/lcurse/modules/waitdlg.py", line 242, in retrieveListOfAddons
    lastpage = self.retrievePartialListOfAddons(page)
  File "/opt/lcurse/modules/waitdlg.py", line 225, in retrievePartialListOfAddons
    lastpage = self.parsePager(pager[0].string)
IndexError: list index out of range
`
Haven't tried latest commit, will do so now and report back.

**Comment by ilu33** [comment]
I had another version from March 2016 and that one works. So it seems that by fixing one issue you created the next :-)

Anyway, thanks maintaining this script, saves me a lot of work during patch times!

**Comment by ephraim** [comment]
> Couldn't find a tree builder with the features you requested: lxml
Please try this: http://stackoverflow.com/questions/21322948/beautifulsoup-wont-recognize-lxml

**Comment by ilu33** [comment]
I Installed libxml2-dev libxslt1-dev as indicated in that thread but it did not change anything. Why should I need developer versions of those libraries anyway?

**Comment by ephraim** [comment]
You miss the pip feature lxml, so just installing the dev libraries won't do it. you will need to pip install lxml too. pip install will compile the lxml stuff. Thats why you need dev libraries.

**Comment by ilu33** [comment]
I don't think I should install a python development environment as a enduser. Especially not if the site warns that it "may leave your system in an inconsistent state." We might be completely on the the wrong track in debugging this.
Does lcurse use python2 or python3?

**Comment by ephraim** [comment]
See first line of lcurse: https://github.com/ephraim/lcurse/blob/master/lcurse#L1

**Comment by ephraim** [comment]
then do a `sudo apt-get install python3-lxml` ...

**Comment by ilu33** [comment]
Yes I just did that and it works! Thank You.
