### ISSUE TITLE
Curse URL has changed

### ISSUE THREAD

**Issue by jwhipp** [ephraim/lcurse#58]
I noted lcurse stopped being able to find a few add-ons.   Going to the curse site, it appears you're now redirected to https://www.curseforge.com/wow/addons/<addon name>.

Looks like lcurse needs to update the source URL now.  Gotta love Curse and their random changes.

**Comment by makerbeleg** [comment]
I confirm, does not work at all for me

**Comment by ggargani** [comment]
Worst thing is that the version number is gone from the first page.... I am trying to fix it in my fork and will submit a PR if I succeed

**Comment by alarofrunetotem** [comment]
pull-request is up. You can get it from my repository (same user of previous comment, I plane hate how github is not smart in managint 2 accounts)

**Comment by ilu33** [comment]
Ephraims version is not working anymore so I tried youts, Alar. This is what I get: 
`python3 /opt/lcurse-alar/lcurse
Folders Preferences/wowfolder /home/.../.wine/drive_c/Program Files (x86)/World of Warcraft
Traceback (most recent call last):
  File "/opt/lcurse-alar/lcurse", line 44, in <module>
    from modules import application
  File "/opt/lcurse-alar/modules/application.py", line 19, in <module>
    from modules import waitdlg
  File "/opt/lcurse-alar/modules/waitdlg.py", line 15, in <module>
    from cryptography.hazmat.primitives.hashes import MD5
ImportError: No module named 'cryptography'
`

**Comment by alar77** [comment]
I am glad it works, I didnt add (at least, not willingly) any dependency, had you already installed ephraims version before or you started straight on with mine?

**Comment by ilu33** [comment]
I had an older version of  Ephraims before. In the version I used there was no cryptography or hash function in waitdlg.py. I think he introduced this sometime ago and made another change stuff recently, see [https://github.com/ephraim/lcurse/commit/ef70ea78882fd19d47cd60afdeb98d4d12382ade](url) - but without eliminating the dependency, contrary to what the title says.
