### ISSUE TITLE
Error update catalogue

### ISSUE THREAD

**Issue by Philmore971** [ephraim/lcurse#68]
Error after update catalog command

Traceback (most recent call last):
  File "/home/philippe/lcurse-master/modules/waitdlg.py", line 424, in run
    self.retrieveListOfAddons()
  File "/home/philippe/lcurse-master/modules/waitdlg.py", line 414, in retrieveListOfAddons
    lastpage = self.retrievePartialListOfAddons(page)
  File "/home/philippe/lcurse-master/modules/waitdlg.py", line 401, in retrievePartialListOfAddons
    href=link.get("href").replace("/download",'')
AttributeError: 'NoneType' object has no attribute 'replace'
Abandon (core dumped)

**Comment by ephraim** [comment]
Will have a look! Thanks for the report

**Comment by vellistaulan** [comment]
Error is the result of Curse's "Enjoy this mod? Support the mod author!" dialog, which appears on some addons. Fix contained in proposed pull request.
